name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.17.0
    steps:
      - uses: actions/checkout@v4
      - name: Install Node Modules
        run: npm install
      - name: Build Production
        run: npm run build --prod
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: node:16.17.0
    steps:
      - uses: actions/checkout@v4
      - name: Install Node Modules
        run: npm install
      - name: Apt Update And Clean
        run: apt-get update; apt-get clean
      - name: Install x11vnc
        run: apt-get install -y x11vnc
      - name: Install xvfb
        run: apt-get install -y xvfb
      - name: Install fluxbox
        run: apt-get install -y fluxbox
      - name: Install wget
        run: apt-get install -y wget
      - name: Install wmctrl
        run: apt-get install -y wmctrl
      - name: Get Linux Signing Key
        run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - name: Get Stable Google Chrome Version
        run: sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - name: Install Google Chrome
        run: apt-get update && apt-get -y install google-chrome-stable
      - name: Create Chrome Path Variable
        run: export CHROME_BIN=/usr/bin/google-chrome
      - name: Run Tests
        run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80'
  deploy:
    needs: [build, unit-test]
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - name: Deploy With Hook
        run: curl -X POST $RENDER_DEPLOY_HOOK > deploy.json
      - uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.json
      - name: Sleep By Two Minutes
        run: sleep 120
  end-to-end-test:
    needs: [deploy]
    runs-on: ubuntu-latest
    container:
      image: node:16.17.0
      options: --user root
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Apt Update And Clean
        run: apt-get update; apt-get clean
      - name: Install Libraries For Google Chrome
        run: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install Node Modules
        run: npm install
      - name: Run Cypress Tests
        run: npm run cypress:run
        env:
          CYPRESS_BASE_URL: https://pokedex-5999.onrender.com/pokedex/#/
      - name: Combine Tests Result On Mochawesome Json
        run: npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
      - name: Generate Mochawesome Folder Report
        run: npx marge mochawesome.json
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results/
